School/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace School.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

School/Controllers/GoverningBodiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using School.Models;

namespace School.Controllers
{
    public class GoverningBodiesController : Controller
    {
        private SchoolDatabaseEntities db = new SchoolDatabaseEntities();
        public ActionResult Index2()
        {
            return View(db.GoverningBodies.ToList());
        }
        // GET: GoverningBodies
        [Authorize]
        public ActionResult Index()
        {
            return View(db.GoverningBodies.ToList());
        }

        // GET: GoverningBodies/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoverningBody governingBody = db.GoverningBodies.Find(id);
            if (governingBody == null)
            {
                return HttpNotFound();
            }
            return View(governingBody);
        }

        // GET: GoverningBodies/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: GoverningBodies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Position")] GoverningBody governingBody)
        {
            if (ModelState.IsValid)
            {
                db.GoverningBodies.Add(governingBody);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(governingBody);
        }

        // GET: GoverningBodies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoverningBody governingBody = db.GoverningBodies.Find(id);
            if (governingBody == null)
            {
                return HttpNotFound();
            }
            return View(governingBody);
        }

        // POST: GoverningBodies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Position")] GoverningBody governingBody)
        {
            if (ModelState.IsValid)
            {
                db.Entry(governingBody).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(governingBody);
        }

        // GET: GoverningBodies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoverningBody governingBody = db.GoverningBodies.Find(id);
            if (governingBody == null)
            {
                return HttpNotFound();
            }
            return View(governingBody);
        }

        // POST: GoverningBodies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GoverningBody governingBody = db.GoverningBodies.Find(id);
            db.GoverningBodies.Remove(governingBody);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

School/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using School.Models;

namespace School.Controllers
{
    public class NewsController : Controller
    {
        private SchoolDatabaseEntities db = new SchoolDatabaseEntities();

        // GET: News
        
        [Authorize]
        public ActionResult Index()
        {
            return View(db.News.ToList());
        }

        public ActionResult ShowNews()
        {
            return View(db.News.ToList());
        }
        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: News/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Event,Description")] News news)
        {
            if (ModelState.IsValid)
            {
                db.News.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(news);
        }

        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Event,Description")] News news)
        {
            if (ModelState.IsValid)
            {
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(news);
        }

        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = db.News.Find(id);
            db.News.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

School/Controllers/StudentRegistrationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using School.Models;

namespace School.Controllers
{
    public class StudentRegistrationsController : Controller
    {
        private SchoolDatabaseEntities db = new SchoolDatabaseEntities();

        // GET: StudentRegistrations
        [Authorize]
        public ActionResult Index()
        {
            return View(db.StudentRegistrations.ToList());
        }

        // GET: StudentRegistrations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentRegistration studentRegistration = db.StudentRegistrations.Find(id);
            if (studentRegistration == null)
            {
                return HttpNotFound();
            }
            return View(studentRegistration);
        }
        [Authorize]
        public ActionResult Create2()
        {
            return View();
        }
        // GET: StudentRegistrations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudentRegistrations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,FathersName,MothersName,PresentAddress,ParmanentAddress,EnrollMentDate,Class,Religion")] StudentRegistration studentRegistration)
        {
            if (ModelState.IsValid)
            {
                db.StudentRegistrations.Add(studentRegistration);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(studentRegistration);
        }

        // GET: StudentRegistrations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentRegistration studentRegistration = db.StudentRegistrations.Find(id);
            if (studentRegistration == null)
            {
                return HttpNotFound();
            }
            return View(studentRegistration);
        }

        // POST: StudentRegistrations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,FathersName,MothersName,PresentAddress,ParmanentAddress,EnrollMentDate,Class,Religion")] StudentRegistration studentRegistration)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studentRegistration).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(studentRegistration);
        }

        // GET: StudentRegistrations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentRegistration studentRegistration = db.StudentRegistrations.Find(id);
            if (studentRegistration == null)
            {
                return HttpNotFound();
            }
            return View(studentRegistration);
        }

        // POST: StudentRegistrations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StudentRegistration studentRegistration = db.StudentRegistrations.Find(id);
            db.StudentRegistrations.Remove(studentRegistration);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

School/Views/Shared/LayoutForUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My School</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    @*<link rel="favicon" href="assets/images/favicon.png">
        <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
        <link rel="stylesheet" href="assets/css/bootstrap.min.css">
        <link rel="stylesheet" href="assets/css/font-awesome.min.css">
        <!-- Custom styles for our template -->
        <link rel="stylesheet" href="assets/css/bootstrap-theme.css" media="screen">
        <link rel="stylesheet" type="text/css" href="assets/css/da-slider.css" />
        <link rel="stylesheet" href="assets/css/style.css">
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->*@


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   
                    <li>@Html.ActionLink("Home", "index", "Default")</li>
                    <li>@Html.ActionLink("About Us", "About", "Home")</li>
                    <li>@Html.ActionLink("Governing Body", "Index2", "GoverningBodies")</li>
                    <li>@Html.ActionLink("Teachers List", "View2", "TeacherRegistrations")</li>
                    <li>@Html.ActionLink("Students Registration", "create", "StudentRegistrations")</li>
                    <li>@Html.ActionLink("Fees", "Index2", "Fees")</li>
                    <li>@Html.ActionLink("Recent News", "ShowNews", "News")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

School/Views/Shared/_HomeLayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>


  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <link rel="favicon" href="assets/images/favicon.png">
  <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
  <link rel="stylesheet" href="assets/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/css/font-awesome.min.css">
  <!-- Custom styles for our template -->
  <link rel="stylesheet" href="assets/css/bootstrap-theme.css" media="screen">
  <link rel="stylesheet" type="text/css" href="assets/css/da-slider.css" />
  <link rel="stylesheet" href="assets/css/style.css">
    <link href="~/Content/Style.css" rel="stylesheet" />
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="assets/js/html5shiv.js"></script>
  <script src="assets/js/respond.min.js"></script>
  <![endif]-->


</head>
<body style="background-color:rgba(165, 206, 143, 0.37)">
    

  <!-- Fixed navbar -->
  <div class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
         
        <!-- Button for smallest screens -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
        <a class="navbar-brand" href="index.html">
            @*<img src="assets/images/logo.png" alt="Techro HTML5 template">*@
          <h1 style="color:steelblue;width:800px;height:50px">My School </h1>
        </a>
      </div>
      
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right mainNav">
            <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
          <li>@Html.ActionLink("About Us", "About", "Home")</li>
          <li>@Html.ActionLink("Governing Body", "Index2", "GoverningBodies")</li>
          <li>@Html.ActionLink("Teachers List", "View2", "TeacherRegistrations")</li>
          <li>@Html.ActionLink("Students Registration", "create", "StudentRegistrations")</li>
          <li>@Html.ActionLink("Fees", "Index2", "Fees")</li>
           <li>@Html.ActionLink("News", "ShowNews", "News")</li>
          <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
          <li>@Html.Partial("_LoginPartial")</li>
        </ul>
         
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
  <!-- /.navbar -->
  <!-- Header -->
  <header id="head">

    <div class="container">
       
</div>
      <div class="banner-content">
        <div id="da-slider" class="da-slider">
          <div class="da-slide">
            <h2>Education For All</h2>
            <p>We Promise to provide better education for all students regardless of their merits.</p>
            <div class="da-img"></div>
          </div>
          <div class="da-slide">
            <h2>Better Environment</h2>
            <p>Ideal Environment for for education for all the children.</p>
            <div class="da-img"></div>
          </div>
          <div class="da-slide">
            <h2>Bright Future</h2>
            <p>We help to ensure bright future for all the children.</p>
            <div class="da-img"></div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- /Header -->
  <div class="container body-content">
    @RenderBody()

    <br />
      <div class="container-fluid">
        <div class="row">
              <div class="col-sm-4" style="background-color:lavender;">
                  <img src="~/Img/p3 - Copy.jpg" />
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>@Html.ActionLink("Read more", "Contact", "Home")
                 
              </div>
              <div class="col-sm-4" style="background-color:lavenderblush;">
                  <img src="~/Img/p3 - Copy.jpg" />
                  <p>Sed ut perspiciatis accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>@Html.ActionLink("Read more", "Contact", "Home")
              </div>
              <div class="col-sm-4" style="background-color:rgba(163, 92, 183, 0.33);">
                  <img src="~/Img/p3 - Copy.jpg" />
                  <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>@Html.ActionLink("Read more", "Contact", "Home")
              </div>
          </div>
      </div>
      <div style="height:100px;width:100%;background-color:rgba(160, 185, 56, 0.43)">

      </div>
      @*<div style="height:80px;width:100% ;background-color:rgba(158, 199, 55, 0.60)">
          <div style="height:80px;width:33%;float:left">

          </div>
          <div style="height:80px;width:33%;float:left">

          </div>
          <div style="height:80px;width:33%;float:left">

          </div>
      </div>*@
    
      <footer style="height:50px;width:100%;background-color:rgba(78, 54, 54, 0.55)">
          <p>&copy; @DateTime.Now.Year - My School</p>
      </footer>
  </div>
  

  <script src="assets/js/modernizr-latest.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="assets/js/jquery.cslider.js"></script>
  <script src="assets/js/custom.js"></script>

</body>
</html>

School/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My School</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

  
  @*<link rel="favicon" href="assets/images/favicon.png">
  <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
  <link rel="stylesheet" href="assets/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/css/font-awesome.min.css">
  <!-- Custom styles for our template -->
  <link rel="stylesheet" href="assets/css/bootstrap-theme.css" media="screen">
  <link rel="stylesheet" type="text/css" href="assets/css/da-slider.css" />
  <link rel="stylesheet" href="assets/css/style.css">
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="assets/js/html5shiv.js"></script>
  <script src="assets/js/respond.min.js"></script>
  <![endif]-->*@


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About Us", "About2", "Home")</li>
                    <li>@Html.ActionLink("Governing Body", "Index", "GoverningBodies")</li>
                    <li>@Html.ActionLink("Teachers Registration","Index", "TeacherRegistrations")</li>
                    <li>@Html.ActionLink("Students Registration", "create2", "StudentRegistrations")</li>
                    <li>@Html.ActionLink("Fees", "Index", "Fees")</li>
                    <li>@Html.ActionLink("News", "Index", "News")</li>
                    <li>@Html.ActionLink("Contact", "Contact2", "Home")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>